[package]
name = "rstest"
version = "0.2.2"
authors = ["Michele d'Amico <michele.damico@gmail.com>"]
homepage = "https://github.com/la10736/rstest"
description = """
A simple `pytest` clone for Rust. It use procedural macro
to implement fixtures and table based tests.
"""
repository = "https://github.com/la10736/rstest"
license = "MIT/Apache-2.0"
keywords = ["test", "fixture"]
categories = ["development-tools::testing"]
readme = "README.md"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["full", "parsing", "extra-traits", "visit"] }
proc-macro2 = { version = "0.4" }
quote = "0.6"
cfg-if = "0.1"

[dev-dependencies]
temp_testdir = "0.2"
lazy_static = "1.1"
toml_edit = "0.1"
pretty_assertions = "*"

[build-dependencies]
rustc_version = "0.2"
